apiVersion: v1
kind: Service
metadata:
  name: churn-app-service
  labels:
    app: churn
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: churn
